In [4]:
import sys
import pandas as pd

In [6]:
#ejercicios pandas 1
#1) importa pandas
#2) Crea una Serie de los numeros 10, 20 and 10.
#3) Crea una Serie con tres objetos: 'rojo', 'verde', 'azul'
#4) Crea un dataframe vacío llamado 'df'
#5) Crea una nueva columna en el dataframe, y asignale la primera serie que has creado
#6) Crea otra columna en el dataframe y asignale la segunda Serie que has creado
#7) # Lee el archivo llamado 'avengers.csv" localizado en la carpeta "data" y crea un DataFrame, llamado 'avengers'. 
#     El archivo está localizado en "data/avengers.csv"
#8) Muestra las primeras 5 filas del DataFrame.
#9) Muestra las primeras 10 filas del DataFrame.
#10) Muestra las últimas 5 filas del DataFrame.
#11) Muestra el tamaño del DataFrame
#12) Muestra los data types del dataframe
#13) Cambia el indice a la columna "fecha_inicio".
#14) Ordena el índice de forma descendiente
#15) Resetea el índice

In [10]:
#no sabia como resolver, asi que investigué. Pandas tiene tres tipos de datos:
#Series
#DataFrames
#Panel

#Las Series se pueden crear a partir de diccionarios -> Series(data=diccionario, index=indices).

#2) Crea una Serie de los numeros 10, 20 and 10.

serie = pd.Series([10,20,10])
serie

0    10
1    20
2    10
dtype: int64

In [13]:
#3) Crea una Serie con tres objetos: 'rojo', 'verde', 'azul'
serie_colores = pd.Series(["rojo", "verde", "azul"])
serie_colores

0     rojo
1    verde
2     azul
dtype: object

In [11]:
#4) Crea un dataframe vacío llamado 'df'
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [12]:
#5) Crea una nueva columna en el dataframe, y asignale la primera serie que has creado
df["Serie"] = serie
df

   Serie
0     10
1     20
2     10

In [14]:
#6) Crea otra columna en el dataframe y asignale la segunda Serie que has creado
df["Colores"] = serie_colores
df

   Serie Colores
0     10    rojo
1     20   verde
2     10    azul

In [16]:
#7) # Lee el archivo llamado 'avengers.csv" localizado en la carpeta "data" y crea un DataFrame, llamado 'avengers'. 
#     El archivo está localizado en "data/avengers.csv"
avengers = pd.read_csv("avengers.csv")
avengers

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

In [17]:
#8) Muestra las primeras 5 filas del DataFrame.

avengers.head(5)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...

In [18]:
#9) Muestra las primeras 10 filas del DataFrame.
avengers.head(10)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
5,http://marvel.wikia.com/Richard_Jones_(Earth-616),Richard Milhouse Jones,612,YES,MALE,1963,NaN
6,http://marvel.wikia.com/Steven_Rogers_(Earth-616),Steven Rogers,3458,YES,MALE,1964,Dies at the end of Civil War. Later comes back.
7,http://marvel.wikia.com/Clint_Barton_(Earth-616),Clinton Francis Barton,1456,YES,MALE,1965,Dies in exploding Kree ship in Averngers Vol. ...
8,http://marvel.wikia.com/Pietro_Maximoff_(Earth...,Pietro Maximoff,769,YES,MALE,1965,Dies in House of M Vol 1 Issue 7. Later comes ...
9,http://marvel.wikia.com/Wanda_Maximoff_(Earth-...,Wanda Maximoff,1214,YES,FEMALE,1965,Dies in Uncanny_Avengers_Vol_1_14. Later comes...

In [19]:
#10) Muestra las últimas 5 filas del DataFrame.
avengers.tail(5)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

In [20]:
#11) Muestra el tamaño del DataFrame

avengers.shape

(173, 7)

In [24]:
#12) Muestra los data types del dataframe
avengers.dtypes

URL              object
nombre           object
n_apariciones     int64
actual           object
genero           object
fecha_inicio      int64
Notes            object
dtype: object

In [26]:
#13) Cambia el indice a la columna "fecha_inicio".
avengers.set_index("fecha_inicio")

,URL,nombre,n_apariciones,actual,genero,Notes
fecha_inicio,,,,,,
1963,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,Merged with Ultron in Rage of Ultron Vol. 1. A...
1963,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,Dies in Secret Invasion V1:I8. Actually was se...
1963,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,"Death: ""Later while under the influence of Imm..."
1963,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,"Dies in Ghosts of the Future arc. However ""he ..."
1963,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...
2013,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,NaN
2014,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,NaN
2014,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,NaN
2014,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,NaN
2015,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,NaN

In [35]:
#14) Ordena el índice de forma descendiente
avengers.sort_index(ascending=False)

,index,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
172,0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
171,1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
170,2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
169,3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
168,4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...,...
4,168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
3,169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
2,170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
1,171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
0,172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

In [36]:
#15) Resetea el índice
avengers = avengers.reset_index()
avengers

,level_0,index,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,0,172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN
1,1,171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
2,2,170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
3,3,169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
4,4,168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
...,...,...,...,...,...,...,...,...,...
168,168,4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
169,169,3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
170,170,2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
171,171,1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
172,172,0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...

In [37]:
!git add *
#actualizamos repositorio

warning: LF will be replaced by CRLF in .ipynb_checkpoints/intro_a_pandas-checkpoint.ipynb.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in intro_a_pandas.ipynb.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .ipynb_checkpoints/ejercicios_pandas_1-checkpoint.ipynb.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in airbnb.csv.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ejercicios_pandas_1.ipynb.
The file will have its original line endings in your working directory

In [38]:
!git commit -m "actualizando repo de ejercicios"

[main f19c93d] actualizando repo de ejercicios
 6 files changed, 16901 insertions(+), 4 deletions(-)
 create mode 100644 .ipynb_checkpoints/ejercicios_pandas_1-checkpoint.ipynb
 create mode 100644 airbnb.csv
 create mode 100644 avengers.csv
 create mode 100644 ejercicios_pandas_1.ipynb

In [39]:
!git push

To https://github.com/pmanciniq/python_ejercicios.git
   450df95..f19c93d  main -> main