#Ejercicio - Busqueda de Alojamiento en Airbnb.

Supongamos que somos un agente de Airbnb localizado en Lisboa, y tenemos que atender peticiones de varios clientes.
Tenemos un archivo llamado airbnb.csv (en la carpeta data) donde tenemos información de todos los alojamientos de Airbnb en 
Lisboa.

En concreto el dataset tiene las siguientes variables:

room_id: el identificador de la propiedad

host_id: el identificador del dueño de la propiedad

room_type: tipo de propiedad (vivienda completa/(habitacion para compartir/habitación privada)

neighborhood: el barrio de Lisboa

reviews: El numero de opiniones

overall_satisfaction: Puntuacion media del apartamento

accommodates: El numero de personas que se pueden alojar en la propiedad

bedrooms: El número de habitaciones

price: El precio (en euros) por noche


##Caso 1

Alicia va a ir a Lisboa durante una semana con su marido y sus 2 hijos. Están buscando un apartamento con habitaciones
separadas para los padres y los hijos. No les importa donde alojarse o el precio, simplemente quieren tener una experiencia 
agradable. Esto significa que solo aceptan lugares con más de 10 críticas con una puntuación mayor de 4. 
Cuando seleccionemos habitaciones para Alicia, tenemos que asegurarnos de ordenar las habitaciones de mejor a peor puntuación. 
Para aquellas habitaciones que tienen la misma puntuación, debemos mostrar antes aquellas con más críticas. 
Debemos darle 3 alternativas.


##Caso 2

Roberto es un casero que tiene una casa en Airbnb. De vez en cuando nos llama preguntando sobre cuales son las críticas 
de su alojamiento. Hoy está particularmente enfadado, ya que su hermana Clara ha puesto una casa en Airbnb 
y Roberto quiere asegurarse de que su casa tiene más críticas que las de Clara. Tenemos que crear un dataframe con 
las propiedades de ambos. Las id de las casas de Roberto y Clara son 97503 y 90387 respectivamente. Finalmente guardamos 
este dataframe como excel llamado "roberto.xlsx"

##Caso 3

Diana va a Lisboa a pasar 3 noches y quiere conocer a gente nueva. Tiene un presupuesto de 50€ para su alojamiento. 
Debemos buscarle las 10 propiedades más baratas, dandole preferencia a aquellas que sean habitaciones 
compartidas (room_type == Shared room), y para aquellas viviendas compartidas debemos elegir aquellas 
con mejor puntuación.

In [2]:
#paso 1, tengo que importar pandas y leer el documento airbnb
import pandas as pd

In [3]:
airbnb = pd.read_csv("airbnb.csv")

In [4]:
airbnb

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,6499,14455,Entire home/apt,Belém,8,5.0,2,1.0,57.0
1,17031,66015,Entire home/apt,Alvalade,0,0.0,2,1.0,46.0
2,25659,107347,Entire home/apt,Santa Maria Maior,63,5.0,3,1.0,69.0
3,29248,125768,Entire home/apt,Santa Maria Maior,225,4.5,4,1.0,58.0
4,29396,126415,Entire home/apt,Santa Maria Maior,132,5.0,4,1.0,67.0
...,...,...,...,...,...,...,...,...,...
13227,19388006,135915593,Entire home/apt,São Vicente,0,0.0,6,3.0,415.0
13228,19393935,5376796,Entire home/apt,Santa Maria Maior,0,0.0,3,1.0,50.0
13229,19396300,6115933,Entire home/apt,Santo António,0,0.0,6,4.0,138.0
13230,19397373,97139334,Entire home/apt,São Vicente,0,0.0,4,1.0,56.0
13231,19400722,28219108,Entire home/apt,Areeiro,0,0.0,5,3.0,75.0

In [27]:
#Caso 1
#Alicia va a ir a Lisboa durante una semana con su marido y sus 2 hijos. Están buscando un apartamento con habitaciones 
#separadas para los padres y los hijos. No les importa donde alojarse o el precio, simplemente quieren tener una 
#experiencia agradable. Esto significa que solo aceptan lugares con más de 10 críticas con una puntuación mayor de 4. 
#Cuando seleccionemos habitaciones para Alicia, tenemos que asegurarnos de ordenar las habitaciones de mejor a peor puntuación.
#Para aquellas habitaciones que tienen la misma puntuación, debemos mostrar antes aquellas con más críticas. 
#Debemos darle 3 alternativas.

#primero revisaremos los datos
#filtro de reviews, todos los lugares con mas de 10 reviews
reviews_10 = airbnb.query('reviews >= 10')
#luego filtro de puntuación mayor a 4
satisfaction_4 = airbnb.query('overall_satisfaction > 4.0')

#se puede hacer ambas consultas en una query usando comparadores AND (&) y OR (|)
df_alicia = airbnb[(airbnb.reviews > 10) & (airbnb.overall_satisfaction > 4.0)]


#ordenamos descendente según la puntuación
df_alicia = df_alicia.sort_values('overall_satisfaction', ascending=False)
df_alicia = df_alicia.sort_values('reviews', ascending=False)

#mostramos 3 alternativas
df_alicia.head(3)

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
120,176153,842219,Entire home/apt,Misericórdia,438,5.0,4,2.0,102.0
1369,1745355,9186518,Entire home/apt,Olivais,419,4.5,5,2.0,50.0
931,1085634,5968047,Entire home/apt,Misericórdia,379,5.0,2,1.0,52.0

In [46]:
##Caso 2
#Roberto es un casero que tiene una casa en Airbnb. De vez en cuando nos llama preguntando sobre cuales son las 
#críticas de su alojamiento. Hoy está particularmente enfadado, ya que su hermana Clara ha puesto una casa en 
#Airbnb y Roberto quiere asegurarse de que su casa tiene más críticas que las de Clara. Tenemos que crear un 
#dataframe con las propiedades de ambos. Las id de las casas de Roberto y Clara son 97503 y 90387 respectivamente. 
#Finalmente guardamos este dataframe como excel llamado "roberto.xlsx"

#primero revisamos los datos de roberto y clara
df_roberto = airbnb.query('room_id == 97503')
#df_roberto
df_clara = airbnb.query('room_id == 90387')
#df_clara

#creamos el df para mostrar a roberto la comparación, y creamos el archivo excel
df_comp = airbnb[airbnb.room_id.isin([97503,90387])].to_excel("roberto.xlsx", index=False)

#vemos el resultado
roberto_excel = pd.read_excel("roberto.xlsx")
roberto_excel

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
0,90387,490050,Private room,Santo António,204,5,2,1,46
1,97503,515924,Private room,Santo António,39,4,2,1,26

In [56]:
##Caso 3
#Diana va a Lisboa a pasar 3 noches y quiere conocer a gente nueva. Tiene un presupuesto de 50€ para su alojamiento. 
#Debemos buscarle las 10 propiedades más baratas, dandole preferencia a aquellas que sean habitaciones 
#compartidas (room_type == Shared room), y para aquellas viviendas compartidas 
#debemos elegir aquellas con mejor puntuación.

#priemro revisamos las habitaciones deseadas
df_diana = airbnb[(airbnb.room_type == 'Shared room')]

#luego ordenamos por puntuación y precio
df_diana = df_diana.query('price <= 50/3')
df_diana

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price
1010,1179457,5799522,Shared room,Santo António,42,4.0,16,1.0,10.0
2838,4010418,12771657,Shared room,Misericórdia,12,4.5,6,1.0,15.0
3562,5557699,28812904,Shared room,Santa Maria Maior,22,4.0,1,1.0,10.0
3597,5610245,29084261,Shared room,Santa Maria Maior,8,4.0,4,1.0,11.0
3738,5823046,29676067,Shared room,Misericórdia,35,4.5,12,1.0,15.0
4319,6691321,28812904,Shared room,Santa Maria Maior,1,0.0,1,1.0,11.0
4353,6728244,28812904,Shared room,Santa Maria Maior,8,4.5,1,1.0,11.0
4354,6728398,28812904,Shared room,Santa Maria Maior,3,2.5,1,1.0,11.0
4921,7737202,40574313,Shared room,Avenidas Novas,44,4.5,4,1.0,13.0
5616,9317561,48360716,Shared room,Arroios,13,4.5,4,1.0,11.0
6056,10397682,32344156,Shared room,Misericórdia,15,5.0,8,1.0,13.0
6058,10398958,32344156,Shared room,Misericórdia,39,4.5,8,1.0,12.0
6282,11014997,32344156,Shared room,Misericórdia,32,4.5,2,1.0,16.0
6284,11015580,32344156,Shared room,Misericórdia,15,4.5,8,1.0,15.0
6639,11693115,28812904,Shared room,Santa Maria Maior,5,3.5,1,1.0,11.0
6640,11693356,28812904,Shared room,Santa Maria Maior,3,4.5,1,1.0,11.0
6641,11693442,28812904,Shared room,Santa Maria Maior,16,4.5,1,1.0,11.0
6894,12041448,64460695,Shared room,Estrela,1,0.0,6,1.0,15.0
6920,12070663,64460695,Shared room,Estrela,5,4.5,7,1.0,13.0
7034,12268067,66077974,Shared room,Arroios,96,5.0,1,1.0,16.0
7059,12299979,66077974,Shared room,Arroios,13,4.5,1,1.0,16.0
7060,12299998,66077974,Shared room,Arroios,49,5.0,1,1.0,13.0
7066,12305540,66077974,Shared room,Arroios,40,5.0,1,1.0,13.0
7584,13116032,72951043,Shared room,Arroios,1,0.0,8,1.0,10.0
7643,13190640,73826302,Shared room,Arroios,51,4.5,6,1.0,13.0
7661,13219674,73826302,Shared room,Arroios,17,4.5,4,1.0,13.0
7662,13220202,73826302,Shared room,Arroios,22,4.5,3,1.0,13.0
7904,13520423,77663975,Shared room,Santa Maria Maior,7,4.5,10,1.0,15.0
7920,13556777,77905788,Shared room,Arroios,1,0.0,7,1.0,15.0
8385,14068386,84472028,Shared room,São Vicente,17,4.5,1,1.0,12.0
8897,14702408,40574313,Shared room,Avenidas Novas,14,4.5,4,1.0,13.0
8908,14708916,91501272,Shared room,Santo António,18,4.5,4,1.0,11.0
8918,14719962,40574313,Shared room,Avenidas Novas,4,5.0,4,1.0,13.0
9061,14932515,91501272,Shared room,Santo António,9,4.5,4,1.0,11.0
9062,14932518,91501272,Shared room,Santo António,7,4.5,4,1.0,11.0
9063,14933037,91501272,Shared room,Santo António,0,0.0,8,1.0,11.0
9065,14933182,91501272,Shared room,Santo António,5,5.0,8,1.0,11.0
9523,15537505,48360716,Shared room,Arroios,2,0.0,4,1.0,15.0
9796,15880914,101182323,Shared room,Belém,7,4.5,8,1.0,16.0
9964,16150682,58899339,Shared room,Avenidas Novas,4,5.0,9,1.0,16.0
10559,16875711,112226564,Shared room,Olivais,15,4.0,1,1.0,15.0
10723,17096560,107813252,Shared room,Areeiro,5,5.0,1,1.0,16.0
10954,17378961,117425901,Shared room,Arroios,0,0.0,10,1.0,16.0
11730,18095471,124601372,Shared room,Santo António,5,4.0,16,1.0,11.0
11787,18154042,124601372,Shared room,Avenidas Novas,1,0.0,6,1.0,11.0
11789,18154378,124601372,Shared room,Santo António,4,4.5,4,1.0,11.0
12042,18347196,107813252,Shared room,Areeiro,0,0.0,1,1.0,16.0
12043,18347279,107813252,Shared room,Areeiro,0,0.0,1,1.0,16.0
12044,18347626,107813252,Shared room,Areeiro,2,0.0,1,1.0,16.0
13148,19314160,135270245,Shared room,Santa Clara,0,0.0,1,1.0,10.0